# Generated by Django 3.2.9 on 2021-11-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontDesigners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'font designer',
                'verbose_name_plural': 'font designers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FontGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'font group',
                'verbose_name_plural': 'font groups',
            },
        ),
        migrations.CreateModel(
            name='AzGoogleFonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('designer', models.ManyToManyField(to='AzGoogleFonts.FontDesigners')),
                ('font_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AzGoogleFonts.fontgroups')),
            ],
            options={
                'verbose_name': 'font',
                'verbose_name_plural': 'fonts',
                'ordering': ('-added',),
            },
        ),
    ]
