# Generated by Django 3.2.9 on 2021-11-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azgooglefonts',
            options={'ordering': ('-added',), 'verbose_name': 'font name', 'verbose_name_plural': 'font names'},
        ),
    ]
