# Generated by Django 3.2.9 on 2021-11-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0003_auto_20211109_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azgooglefonts',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AzGoogleFonts.fontdesigners'),
        ),
    ]
