# Generated by Django 3.2.9 on 2021-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0004_alter_azgooglefonts_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontdesigners',
            name='slug',
            field=models.SlugField(default='hell'),
        ),
        migrations.AddField(
            model_name='fontgroups',
            name='slug',
            field=models.SlugField(default='hello'),
        ),
    ]
