# Generated by Django 3.2.9 on 2021-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0005_auto_20211109_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontdesigners',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='fontgroups',
            name='slug',
            field=models.SlugField(),
        ),
    ]
