# Generated by Django 3.2.9 on 2021-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0008_alter_azgooglefonts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azgooglefonts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fontdesigners',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fontgroups',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
