# Generated by Django 3.2.9 on 2021-11-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzGoogleFonts', '0009_auto_20211109_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azgooglefonts',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fontdesigners',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fontgroups',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
